esphome:
  name: teste1
  friendly_name: teste1
  platform: ESP8266
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "0KOGdhPcap8q982D/TRYngQSxjdCDqZkX5FDkuW1Aqw="

ota:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    # Set this to the IP of the ESP
    static_ip: 192.168.0.138
    # Set this to the IP address of the router. Often ends with .1
    gateway: 192.168.0.1
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0
  ap:

captive_portal:

web_server:

sensor:
  - platform: dht
    pin: D1
    temperature:
      name: "My Temperature"
    humidity:
      name: "My Humidity"
    update_interval: 60s
    model: DHT11
  - platform: dht
    pin: D2
    temperature:
      name: "Temperature sensor 2"
    humidity:
      name: "Humidity sensor 2"
    update_interval: 60s
